#ifndef BASE_HPP
#define BASE_HPP

#include "../inc/common.hpp"

#include "Entity.hpp"
#include "BasicShape.hpp"
#include "BasicUtils.hpp"


class Base {
private:
    // Saves the amount of time generated by the timeUtil.
    BasicUtils ut;
    float totalTime;

    sf::RenderWindow window;
    sf::View view;

    Entity player;
    std::vector<sf::FloatRect> playerBorders;
    int playerMoveDirection; // 0 = up, 1 = right, 2 = down, 3 = left;
    sf::Vector2f playerMoveAmount;
    
    std::vector<BasicShape> collides;

public:

    // Init class.
    Base();

    // Init functions.
    void createWindow();
    void createPlayer();
    void designLevel(int/*, int*/); // 1 = Rooms

    // Required by designLevel().
    void convertCoords(std::string, sf::Vector2f&);
    void fillLevelArray(sf::Vector2f, sf::Vector2f, std::vector<std::string>, std::vector<BasicShape>&);

    // Main Functions.
    bool gameLoop();
    bool checkControls();

    // Required by checkControls().
    float calculateFrameStep();
    void checkMoves();

    // Required by checkMoves().
    void updatePlayerBorders();

    void drawWindow();
};

#endif
